// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3824.PrototypePrinted.commands;

import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc3824.PrototypePrinted.Constants;
import org.usfirst.frc3824.PrototypePrinted.Robot;
import org.usfirst.frc3824.PrototypePrinted.subsystems.Chassis.AnglePIDOutput;


/**
 *
 */
public class ChassisTurnToImageTarget extends Command
{
	private PIDController turnController;
	private ImageDataPIDInput imageInput;
	private AnglePIDOutput angleOutput;


	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS


	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS


	public ChassisTurnToImageTarget()
	{
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.chassis);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        angleOutput = Robot.chassis.new AnglePIDOutput();
        imageInput = new ImageDataPIDInput();
        turnController = new PIDController(Constants.IMAGE_TURN_P, Constants.IMAGE_TURN_I, Constants.IMAGE_TURN_P, imageInput, angleOutput);
	}

	// Called just before this Command runs the first time
	protected void initialize()
	{
		turnController.reset();
		turnController.setSetpoint(0.0);

		// enable the PID
		turnController.enable();
	}

	// Called repeatedly when this Command is scheduled to run
	protected void execute()
	{
		SmartDashboard.putNumber("Gyro", Robot.chassis.getGyroValue());
	}

	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished()
	{
		return false;
	}

	// Called once after isFinished returns true
	protected void end()
	{
		// disable the PID and stop the robot
		turnController.disable();
		Robot.chassis.getRobotDrive().arcadeDrive(0, 0);
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted()
	{
		// call the end method
		this.end();
	}
	
	
	/**
	 * Class declaration for the PIDSource
	 */
	public class ImageDataPIDInput implements PIDSource
	{
		/**
		 * Virtual function to calculate pid value 
		 */
		public double pidGet()
		{
			// Drive the robot given the speed and direction

			return 0.0;
		}
		
		@Override
		public PIDSourceType getPIDSourceType()
		{
			return PIDSourceType.kDisplacement;
		}
		
		@Override
		public void setPIDSourceType(PIDSourceType pidSource)
		{
			// Do nothing.. Right now leave source type as displacement
		}
	}

	
}
